name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.18.0'
          check-latest: true
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check environment
        run: |
          echo "Node:"
          node --version

          echo "npm:"
          npm --version

          echo "Vitest:"
          npm list vitest

          echo "Vite:"
          npm list vite

          echo "Rolldown:"
          npm list rolldown  

      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test:run
      - name: Build production version
        run: npm run build              
