name: Docker

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      # 1. Download our repository onto the GitHub runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Build Docker image
      - name: Build Docker image
        run: docker build -t ecommerce:latest 